name: gloc-gpu
channels:
  - rapidsai
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - cuda-version>=12.2,<=12.9
  - cuml=26.06
  - cupy
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - scikit-optimize
  - faiss-cpu=1.14.3
  - matplotlib
  - matplotlib-venn
  - seaborn
  - shap
  - optuna
  - pytest
  - ipykernel
  - openpyxl
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch
      - torchvision
      - UpSetPlot==0.9.0
      - munkres==1.1.4
      - unicodedata2==17.0.1