name: gloc-cpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - scikit-optimize
  - matplotlib
  - matplotlib-venn
  - seaborn
  - shap
  - optuna
  - pytest
  - ipykernel
  - openpyxl
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch
      - torchvision
      - faiss-cpu=1.14.3
      - UpSetPlot==0.9.0
      - munkres==1.1.4
      - unicodedata2==17.0.1