name: gloc
channels:
  - conda-forge
  - rapidsai
  - pytorch
  - nvidia
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alembic=1.18.4
  - annotated-types=0.7.0
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.6.0
  - aws-c-http=0.10.12
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.11.5
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.4
  - aws-sdk-cpp=1.11.747
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.4.22
  - cachetools=7.0.6
  - cairo=1.18.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - colorlog=6.10.1
  - contourpy=1.3.3
  - cpython=3.12.13
  - cuda-bindings=13.2.0
  - cuda-cccl_linux-64=13.2.75
  - cuda-core=0.7.0
  - cuda-crt-dev_linux-64=13.2.78
  - cuda-crt-tools=13.2.78
  - cuda-cudart=13.2.75
  - cuda-cudart-dev=13.2.75
  - cuda-cudart-dev_linux-64=13.2.75
  - cuda-cudart-static=13.2.75
  - cuda-cudart-static_linux-64=13.2.75
  - cuda-cudart_linux-64=13.2.75
  - cuda-cuobjdump=13.2.78
  - cuda-cupti=13.2.75
  - cuda-nvcc-dev_linux-64=13.2.78
  - cuda-nvcc-impl=13.2.78
  - cuda-nvcc-tools=13.2.78
  - cuda-nvdisasm=13.2.78
  - cuda-nvrtc=13.2.78
  - cuda-nvtx=13.2.75
  - cuda-nvvm-dev_linux-64=13.2.78
  - cuda-nvvm-impl=13.2.78
  - cuda-nvvm-tools=13.2.78
  - cuda-pathfinder=1.5.3
  - cuda-profiler-api=13.2.75
  - cuda-python=13.2.0
  - cuda-version=13.2
  - cudf=26.04.00
  - cudnn=9.21.1.3
  - cuml=26.04.00
  - cupy=14.0.1
  - cupy-core=14.0.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - dlpack=0.8
  - double-conversion=3.4.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - faiss-cpu=1.14.1
  - filelock=3.29.0
  - fmt=12.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.62.1
  - freetype=2.14.3
  - fsspec=2026.3.0
  - future=1.0.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.3.0
  - graphite2=1.3.14
  - greenlet=3.5.0
  - harfbuzz=14.1.0
  - icu=78.3
  - imbalanced-learn=0.14.1
  - importlib-metadata=8.8.0
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - keyutils=1.6.3
  - kiwisolver=1.5.0
  - krb5=1.22.2
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.1.0
  - libabseil=20260107.1
  - libarrow=23.0.1
  - libarrow-acero=23.0.1
  - libarrow-compute=23.0.1
  - libarrow-dataset=23.0.1
  - libarrow-substrait=23.0.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang13=22.1.3
  - libcrc32c=1.1.2
  - libcublas=13.4.0.1
  - libcublas-dev=13.4.0.1
  - libcudf=26.04.00
  - libcudnn=9.21.1.3
  - libcudnn-dev=9.21.1.3
  - libcudss=0.7.1.4
  - libcufft=12.2.0.46
  - libcufile=1.17.1.22
  - libcufile-dev=1.17.1.22
  - libcuml=26.04.00
  - libcups=2.3.3
  - libcurand=10.4.2.55
  - libcurand-dev=10.4.2.55
  - libcurl=8.19.0
  - libcusolver=12.2.0.1
  - libcusolver-dev=12.2.0.1
  - libcusparse=12.7.10.1
  - libcusparse-dev=12.7.10.1
  - libcuvs=26.04.00
  - libcuvs-headers=26.04.00
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.5
  - libfaiss=1.14.1
  - libffi=3.5.2
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=3.3.0
  - libgoogle-cloud-storage=3.3.0
  - libgrpc=1.78.1
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.4.1
  - libkvikio=26.04.00
  - liblapack=3.11.0
  - libllvm22=22.1.3
  - liblzma=5.8.3
  - libmagma=2.9.0
  - libnghttp2=1.68.1
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvcomp=5.1.0.21
  - libnvcomp-dev=5.1.0.21
  - libnvjitlink=13.2.78
  - libnvjpeg=13.1.0.48
  - libnvptxcompiler-dev=13.2.78
  - libnvptxcompiler-dev_linux-64=13.2.78
  - libopenblas=0.3.32
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.26.0
  - libopentelemetry-cpp-headers=1.26.0
  - libparquet=23.0.1
  - libpciaccess=0.18
  - libpng=1.6.58
  - libpq=18.3
  - libprotobuf=6.33.5
  - libraft=26.04.00
  - libraft-headers=26.04.00
  - libraft-headers-only=26.04.00
  - libre2-11=2025.11.05
  - librmm=26.04.00
  - libsqlite=3.53.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsvs-runtime=0.2.0
  - libsystemd0=260.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.10.0
  - libucxx=0.49.00
  - libudev1=260.1
  - libutf8proc=2.11.3
  - libuuid=2.42.1
  - libuv=1.51.0
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.3
  - libxml2-16=2.15.3
  - libxslt=1.1.43
  - libzlib=1.3.2
  - llvm-openmp=22.1.3
  - llvmlite=0.46.0
  - lz4-c=1.10.0
  - mako=1.3.12
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-venn=1.1.2
  - mdurl=0.1.2
  - mkl=2025.3.1
  - mpc=1.4.0
  - mpfr=4.2.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - nccl=2.29.7.1
  - ncurses=6.5
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - numba=0.64.0
  - numba-cuda=0.28.2
  - numpy=2.4.3
  - nvidia-ml-py=13.595.45
  - nvtx=0.2.15
  - openjpeg=2.5.4
  - openldap=2.6.13
  - openpyxl=3.1.5
  - openssl=3.6.2
  - opt_einsum=3.4.0
  - optree=0.19.0
  - optuna=3.6.1
  - orc=2.3.0
  - packaging=26.1
  - pandas=2.3.3
  - patsy=1.0.2
  - pcre2=10.47
  - pillow=12.2.0
  - pip=26.0.1
  - pixman=0.46.4
  - pluggy=1.6.0
  - progressbar2=4.5.0
  - prometheus-cpp=1.3.0
  - pthread-stubs=0.4
  - pyaml=26.2.1
  - pyarrow=23.0.1
  - pyarrow-core=23.0.1
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pydantic=2.13.4
  - pydantic-core=2.46.4
  - pygam=0.12.0
  - pygments=2.20.0
  - pylibcudf=26.04.00
  - pylibraft=26.04.00
  - pyparsing=3.3.2
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pyside6=6.11.0
  - pytest=9.0.3
  - python=3.12.13
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.13
  - python-tzdata=2026.1
  - python-utils=3.9.1
  - python_abi=3.12
  - pytorch=2.10.0
  - pytz=2026.1.post1
  - pyyaml=6.0.3
  - qhull=2020.2
  - qt6-main=6.11.0
  - rapids-logger=0.2.3
  - rdma-core=61.0
  - re2=2025.11.05
  - readline=8.3
  - rich=15.0.0
  - rmm=26.04.00
  - ruff=0.15.15
  - s2n=1.7.1
  - scikit-learn=1.8.0
  - scikit-optimize=0.10.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - shap=0.51.0
  - six=1.17.0
  - sklearn-compat=0.1.5
  - sleef=3.9.0
  - slicer=0.0.8
  - snappy=1.2.2
  - sqlalchemy=2.0.49
  - statsmodels=0.14.6
  - sympy=1.14.0
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.4.1
  - torchvision=0.26.0
  - tornado=6.5.5
  - tqdm=4.67.3
  - treelite=4.7.0
  - triton=3.6.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucx=1.20.0
  - ucxx=0.49.00
  - unicodedata2=17.0.1
  - upsetplot=0.9.0
  - wayland=1.25.0
  - wheel=0.46.3
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.47
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xorg-xorgproto=2025.1
  - yaml=0.2.5
  - zipp=3.23.1
  - zlib=1.3.2
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - basedpyright==1.39.8
      - comm==0.2.3
      - debugpy==1.8.21
      - decorator==5.3.1
      - executing==2.2.1
      - ipykernel==7.2.0
      - ipython==9.14.1
      - ipython-pygments-lexers==1.1.1
      - jedi==0.20.0
      - jupyter-client==8.9.0
      - jupyter-core==5.9.1
      - matplotlib-inline==0.2.2
      - nest-asyncio==1.6.0
      - nodejs-wheel-binaries==24.16.0
      - parso==0.8.7
      - pexpect==4.9.0
      - platformdirs==4.10.0
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pylsl==1.18.2
      - pyzmq==27.1.0
      - setuptools==81.0.0
      - stack-data==0.6.3
      - traitlets==5.15.1
      - wcwidth==0.8.0