models:
  - EGB
  - KNN
  - RF
model_type:
  - Complete
  - Explicit
random_seed: 42
data_path: /home/gloc/G-LOC-Prediction/data
shared_data_parameters:
  subject_to_analyze: null
  trial_to_analyze: null
  analysis_type: 2
  remove_NaN_trials: true
  impute_file_name: imputed_data.pkl
  save_impute: false
  load_impute: false
  should_impute: true
  output_feature_dtype: float32
  faiss_index_type: cpu
advanced_data_parameters:
  num_splits: 10
  kfold_ID: 0
  n_neighbors: 4
  baseline_window: 32.5
traditional_data_parameters:
  backstep: 0
  data_rate: 25
  offset: 0
  time_start: 0
sensor_ablation_parameters:
  enabled: true
  streams:
    - - ECG
      - HR
      - BR
      - Temperature
    - - EEG
    - - Pupil
    - - Centrifuge
    - - Participant
    - - Centrifuge
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
    - - ECG
      - HR
      - BR
      - Temperature
      - Pupil
    - - ECG
      - HR
      - BR
      - Temperature
      - Centrifuge
    - - ECG
      - HR
      - BR
      - Temperature
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - Centrifuge
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Pupil
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Centrifuge
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Centrifuge
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - Pupil
      - Centrifuge
    - - ECG
      - HR
      - BR
      - Temperature
      - Pupil
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - Pupil
      - Centrifuge
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Pupil
      - Centrifuge
      - Participant
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Pupil
      - Centrifuge
    - - ECG
      - HR
      - BR
      - Temperature
      - EEG
      - Pupil
      - Participant
    - - EEG
      - Pupil
    - - EEG
      - Centrifuge
      - Participant
    - - EEG
      - Centrifuge
    - - EEG
      - Participant
    - - EEG
      - Pupil
      - Centrifuge
      - Participant
    - - EEG
      - Pupil
      - Centrifuge
    - - EEG
      - Pupil
      - Participant
    - - Pupil
      - Centrifuge
      - Participant
    - - Pupil
      - Centrifuge
    - - Pupil
      - Participant