[pytest]
pythonpath = .
log_cli = true
log_cli_level = DEBUG
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
markers =
    integration: marks end-to-end or data-heavy integration tests