data_path: /home/gloc/G-LOC-Prediction/data/
shared_data_parameters:
  subject_to_analyze: null
  trial_to_analyze: null
  analysis_type: 2
  remove_NaN_trials: true
  impute_file_name: imputed_data.pkl
  save_impute: false
  load_impute: false
  impute_phase: pre_feature
  output_feature_dtype: float32
advanced_data_parameters:
  n_neighbors: 4
  baseline_window: 32.5
traditional_data_parameters:
  backstep: 0
  data_rate: 25
  offset: 0
  time_start: 0

sensor_ablation:
  training:
    enabled: true
    save_results_folder: Results/Sensor_Ablation
    median_hyperparameters_folder: Results/Cross_Validation
    # Mode-specific parameters
    models: [KNN, EGB]
    model_type: !ModelType [Complete, Explicit]
    manual_ablation: true
    random_seed: 42
    num_splits: 10
    streams:
      - [EEG]
      - [EEG, Pupil]
      - [EEG, Pupil, Participant]