data_path: /home/jasper_shen/Projects/G-LOC-Prediction/data_reduced
shared_data_parameters:
  subject_to_analyze: null
  trial_to_analyze: null
  analysis_type: 2
  remove_NaN_trials: true
  impute_file_name: imputed_data.pkl
  save_impute: false
  load_impute: false
  impute_phase: pre_feature
  output_feature_dtype: float32
advanced_data_parameters:
  n_neighbors: 4
  baseline_window: 32.5
  horizon: 1
traditional_data_parameters:
  backstep: 0
  data_rate: 25
  offset: 1
  time_start: 0
cross_validation:
  enabled: false
  # Mode-specific parameters
  #  models: [ EGB, KNN, LDA, LogReg, RF, SVM, LSTM, TCN, Trans, LogRegTS ] <- All models
  models: [ KNN, LSTM ]
  model_type: !ModelType [ Complete, Explicit ]
  random_seed: 42
  num_splits: 2
  save_results_folder: Results/Cross_Validation_Temporal_Test
  class_weight: null
  advanced_hpo:
    use_sampler: true
    final_early_stop: true
    objective_var: F1
    trials: 10

sensor_ablation:
  training:
    enabled: false
    manual_ablation: false
    save_results_folder: Results/Sensor_Ablation_Test
    median_hyperparameters_folder: Results/Cross_Validation_Test
    models: [ KNN, LSTM ]
    model_type: !ModelType [ Complete, Explicit ]
    random_seed: 42
    num_splits: 2
    class_weight: balanced
    streams:
      - [ EEG ]
      - [ EEG, Pupil, Participant ]
  review:
    enabled: true
    save_results_folder: Results/Sensor_Ablation_Test
    # Mode-specific parameters for review
    models: [ KNN, LSTM ]
    model_type: !ModelType [ Complete, Explicit ]
    stream_groups:
      - [ EEG ]
      - [ EEG, Pupil, Participant ]
    sort_streams_by_median: true

feature_space_review:
  enabled: false
  # Mode-specific parameters
  models: [ KNN, LogReg ]
  model_type: !ModelType [ Complete, Explicit ]
  median_hyperparameters_folder: Results/Cross_Validation